"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var s = require("./project.module.scss");
var Projects = function () {
    return (React.createElement("div", { className: s.projects + " " + s.projects__container },
        React.createElement("div", { className: s.projects__row },
            React.createElement("div", { className: s.projects__item },
                React.createElement("div", { className: s.project__container },
                    React.createElement("div", { className: s.project__image },
                        React.createElement("img", { src: "https://cdn.pixabay.com/photo/2015/03/30/20/33/heart-700141__480.jpg", alt: "Image not found!" })),
                    React.createElement("div", { className: s.project__name },
                        React.createElement("h2", null, "Name")),
                    React.createElement("div", { className: s.project__status },
                        React.createElement("h2", null, "Status")),
                    React.createElement("div", { className: s.project__btn },
                        React.createElement("button", null, "Read More")))),
            React.createElement("div", { className: s.projects__item },
                React.createElement("div", { className: s.project__container },
                    React.createElement("div", { className: s.project__image },
                        React.createElement("img", { src: "https://cdn.pixabay.com/photo/2015/03/30/20/33/heart-700141__480.jpg", alt: "Image not found!" })),
                    React.createElement("div", { className: s.project__name },
                        React.createElement("h2", null, "Name")),
                    React.createElement("div", { className: s.project__status },
                        React.createElement("h2", null, "Status")),
                    React.createElement("div", { className: s.project__btn },
                        React.createElement("button", null, "Read More")))),
            React.createElement("div", { className: s.projects__item },
                React.createElement("div", { className: s.project__container },
                    React.createElement("div", { className: s.project__image },
                        React.createElement("img", { src: "https://cdn.pixabay.com/photo/2015/03/30/20/33/heart-700141__480.jpg", alt: "Image not found!" })),
                    React.createElement("div", { className: s.project__name },
                        React.createElement("h2", null, "Name")),
                    React.createElement("div", { className: s.project__status },
                        React.createElement("h2", null, "Status")),
                    React.createElement("div", { className: s.project__btn },
                        React.createElement("button", null, "Read More"))))),
        React.createElement("div", { className: s.projects__row },
            React.createElement("div", { className: s.projects__item },
                React.createElement("div", { className: s.project__container },
                    React.createElement("div", { className: s.project__image },
                        React.createElement("img", { src: "https://cdn.pixabay.com/photo/2015/03/30/20/33/heart-700141__480.jpg", alt: "Image not found!" })),
                    React.createElement("div", { className: s.project__name },
                        React.createElement("h2", null, "Name")),
                    React.createElement("div", { className: s.project__status },
                        React.createElement("h2", null, "Status")),
                    React.createElement("div", { className: s.project__btn },
                        React.createElement("button", null, "Read More")))),
            React.createElement("div", { className: s.projects__item },
                React.createElement("div", { className: s.project__container },
                    React.createElement("div", { className: s.project__image },
                        React.createElement("img", { src: "https://cdn.pixabay.com/photo/2015/03/30/20/33/heart-700141__480.jpg", alt: "Image not found!" })),
                    React.createElement("div", { className: s.project__name },
                        React.createElement("h2", null, "Name")),
                    React.createElement("div", { className: s.project__status },
                        React.createElement("h2", null, "Status")),
                    React.createElement("div", { className: s.project__btn },
                        React.createElement("button", null, "Read More")))),
            React.createElement("div", { className: s.projects__item },
                React.createElement("div", { className: s.project__container },
                    React.createElement("div", { className: s.project__image },
                        React.createElement("img", { src: "https://cdn.pixabay.com/photo/2015/03/30/20/33/heart-700141__480.jpg", alt: "Image not found!" })),
                    React.createElement("div", { className: s.project__name },
                        React.createElement("h2", null, "Name")),
                    React.createElement("div", { className: s.project__status },
                        React.createElement("h2", null, "Status")),
                    React.createElement("div", { className: s.project__btn },
                        React.createElement("button", null, "Read More")))))));
};
exports.default = Projects;
//# sourceMappingURL=Projects.js.map